export type TransactionAction =
  | 'swap'
  | 'stake'
  | 'unstake'
  | 'lend'
  | 'borrow'
  | 'withdraw'
  | 'transfer'
  | 'bridge';

export type RiskTier = 'fast' | 'standard' | 'high-scrutiny';

export interface IntentManifest {
  // Identity
  proposalId:     string;    // crypto.randomUUID() — generated by the submitting agent
  agentId:        string;    // Soroban identity of the submitting agent
  agentSignature: string;    // agent signs the full manifest with its Stellar keypair

  // The transaction
  action:         TransactionAction;
  fromAsset:      string;    // e.g. "XLM", "USDC", Stellar asset code
  toAsset:        string;
  amount:         string;    // as string to avoid float precision issues
  protocol:       string;    // e.g. "soroswap", "blend", "phoenix"
  protocolAddress: string;   // Soroban contract address of the target protocol

  // Safety parameters
  maxSlippage:    number;    // e.g. 0.02 = 2% maximum accepted slippage
  deadline:       number;    // unix timestamp — tx must execute before this
  minReceived:    string;    // minimum output amount agent will accept

  // Intent provenance — this is what makes Quorum unique
  humanPrompt:    string;    // the original natural language instruction to the agent
  agentReasoning: string;    // why the agent chose these specific parameters

  // Metadata
  timestamp:      number;    // Date.now() when manifest was created
  network:        'testnet' | 'mainnet';
}

export interface ArbiterVerdict {
  proposalId:  string;
  arbiterId:   string;
  decision:    'approve' | 'reject';
  confidence:  number;       // 0.0 to 1.0
  reasoning:   string;       // why the arbiter approved or rejected
  flags:       string[];     // specific issues found (empty if approved)
  timestamp:   number;
  signature:   string;       // arbiter signs its own verdict with its Stellar keypair
}

export interface QuorumDecision {
  proposalId:       string;
  outcome:          'approved' | 'rejected';
  verdicts:         ArbiterVerdict[];
  approvalCount:    number;
  requiredCount:    number;   // based on risk tier
  riskTier:         RiskTier;
  executionTxHash?: string;   // set after execution if approved
  incidentId?:      string;   // set if rejected and pattern was new
  timestamp:        number;
}
